{{ if .Values.vault.enabled }}
apiVersion: stash.appscode.com/v1beta1
kind: Task
metadata:
  name: 'vault-restore-1.10.3'
  labels:
    {{- include "stash-catalog.labels" . | nindent 4 }}
spec:
  steps:
  - name: vault-restore-1.10.3
    params:
    - name: outputDir
      value: /stash-tmp/output
  - name: update-status
    params:
    - name: outputDir
      value: /stash-tmp/output
{{ end }}
