apiVersion: stash.appscode.com/v1beta1
kind: Function
metadata:
  name: nats-restore-2.6.1
spec:
  args:
  - restore-nats
  - --provider=${REPOSITORY_PROVIDER:=}
  - --bucket=${REPOSITORY_BUCKET:=}
  - --endpoint=${REPOSITORY_ENDPOINT:=}
  - --region=${REPOSITORY_REGION:=}
  - --path=${REPOSITORY_PREFIX:=}
  - --secret-dir=/etc/repository/secret
  - --scratch-dir=/tmp
  - --enable-cache=${ENABLE_CACHE:=true}
  - --max-connections=${MAX_CONNECTIONS:=0}
  - --hostname=${HOSTNAME:=}
  - --source-hostname=${SOURCE_HOSTNAME:=}
  - --interim-data-dir=${INTERIM_DATA_DIR}
  - --nats-args=${args:=}
  - --streams=${streams:=}
  - --overwrite=${overwrite:=false}
  - --wait-timeout=${waitTimeout:=300}
  - --namespace=${NAMESPACE:=default}
  - --appbinding=${TARGET_NAME:=}
  - --snapshot=${RESTORE_SNAPSHOTS:=}
  - --output-dir=${outputDir:=}
  - --license-apiservice=${LICENSE_APISERVICE:=}
  image: stashed/stash-nats:2.6.1
  volumeMounts:
  - mountPath: /etc/repository/secret
    name: ${secretVolume}
