{{ if .Values.elasticsearch.enabled }}
apiVersion: stash.appscode.com/v1beta1
kind: Task
metadata:
  name: 'elasticsearch-restore-6.4.0'
  labels:
    {{- include "stash-catalog.labels" . | nindent 4 }}
spec:
  steps:
  - name: elasticsearch-restore-6.4.0
    params:
    - name: outputDir
      value: /stash-tmp/output
  - name: update-status
    params:
    - name: outputDir
      value: /stash-tmp/output
{{ end }}
