# https://github.com/helm/charts/blob/master/test/README.md#providing-custom-test-values
license: ""
operator:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
crdInstaller:
  registry: appscodeci
  tag: latest
  securityContext:
    seccompProfile:
      type: RuntimeDefault
pushgateway:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
cleaner:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
