apiVersion: stash.appscode.com/v1beta1
kind: Task
metadata:
  name: perconaxtradb-backup-5.7.0
spec:
  steps:
  - name: perconaxtradb-backup-5.7.0
    params:
    - name: outputDir
      value: /tmp/output
    - name: secretVolume
      value: secret-volume
  - name: update-status
    params:
    - name: outputDir
      value: /tmp/output
    - name: secretVolume
      value: secret-volume
  volumes:
  - name: secret-volume
    secret:
      secretName: ${REPOSITORY_SECRET_NAME}
