apiVersion: stash.appscode.com/v1beta1
kind: Task
metadata:
  name: nats-backup-2.8.2
spec:
  steps:
  - name: nats-backup-2.8.2
    params:
    - name: outputDir
      value: /tmp/output
  - name: update-status
    params:
    - name: outputDir
      value: /tmp/output
