apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: stash-backup-job
  labels:
    {{- include "stash.labels" . | nindent 4 }}
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
  - "*" # backup job need to access all types of volume as user may backup any types of volume
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
