apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: stash-backupsession-cron
  labels:
    {{- include "stash.labels" . | nindent 4 }}
spec:
  privileged: false
  allowPrivilegeEscalation: false
  hostNetwork: false
  hostIPC: false
  hostPID: false
  volumes:
  - secret # kubernetes mount service account token secret into the pod. so we need to give permission to mount secret volume
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
