apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "stash.fullname" . }}-cleaner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stash.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 120
  template:
    spec:
      serviceAccountName: {{ template "stash.serviceAccountName" . }}
      containers:
      - name: busybox
        image: {{ .Values.cleaner.registry }}/{{ .Values.cleaner.repository }}:{{ .Values.cleaner.tag }}
        command:
          - sh
          - -c
          - "sleep 2; \
           kubectl delete validatingwebhookconfigurations admission.stash.appscode.com || true; \
           kubectl delete mutatingwebhookconfiguration admission.stash.appscode.com || true; \
           kubectl delete apiservice v1alpha1.admission.stash.appscode.com || true; \
           kubectl delete functions.stash.appscode.com update-status pvc-backup pvc-restore || true; \
           kubectl delete tasks.stash.appscode.com pvc-backup pvc-restore"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
      restartPolicy: Never
