apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "stash.fullname" . }}
  labels:
    {{- include "stash.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ["*"]
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs: ["get", "patch", "delete"]
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs: ["delete", "get", "list", "watch", "patch"]
- apiGroups:
  - stash.appscode.com
  resources:
  - "*"
  verbs: ["*"]
- apiGroups:
  - appcatalog.appscode.com
  resources:
  - "*"
  verbs: ["*"]
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch", "patch"]
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list", "watch", "create", "delete", "patch"]
- apiGroups:
  - ""
  resources:
  - namespaces
  - replicationcontrollers
  verbs: ["get", "list", "watch", "patch"]
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs: ["create", "update", "get", "delete"]
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs: ["get","list","watch", "create", "patch"]
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  - endpoints
  verbs: ["get"]
- apiGroups:
  - ""
  resources:
  - events
  verbs: ["create"]
- apiGroups:
  - ""
  resources:
  - nodes
  verbs: ["list"]
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs: ["get", "create", "list", "delete", "deletecollection"]
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs: ["get", "create", "patch", "delete"]
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - roles
  - rolebindings
  - clusterrolebindings
  verbs: ["get", "create", "delete", "patch"]
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs: ["get", "list", "watch", "patch"]
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs: ["use"]
  resourceNames:
  - {{ template "stash.fullname" . }}
  - stash-backupsession-cron
  - stash-backup-job
  - stash-restore-job
  {{- range $x := .Values.additionalPodSecurityPolicies }}
  - {{ $x }}
  {{- end }}
- apiGroups:
    - snapshot.storage.k8s.io
  resources:
    - volumesnapshots
    - volumesnapshotcontents
    - volumesnapshotclasses
  verbs: ["create", "get", "list", "watch", "patch", "delete"]
- apiGroups:
    - storage.k8s.io
  resources:
    - storageclasses
  verbs: ["get"]
