apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "stash.fullname" . }}
  labels:
    {{- include "stash.labels" . | nindent 4 }}
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
  - "*" # operator need to access all types of volume
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
