{{- if and (eq .Values.monitoring.agent "prometheus.io/coreos-operator") (or .Values.monitoring.backup .Values.monitoring.operator) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "stash.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.monitoring.prometheus.namespace }}
  labels:
    {{- if .Values.monitoring.serviceMonitor.labels }}
    {{- range $key, $val := .Values.monitoring.serviceMonitor.labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
    {{- else }}
    app: "{{ template "stash.name" . }}"
    release: "{{ .Release.Name }}"
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: "{{ template "stash.name" . }}"
      release: "{{ .Release.Name }}"
  endpoints:
  {{- if .Values.monitoring.backup }}
  - port: pushgateway
    honorLabels: true
  {{- end }}
  {{- if .Values.monitoring.operator }}
  - port: api
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/secrets/{{ template "stash.fullname" . }}-apiserver-cert/tls.crt
      serverName: "{{ template "stash.fullname" . }}.{{ .Release.Namespace }}.svc"
  {{- end }}
{{- end }}
