{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "stash.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stash.labels" . | nindent 4 }}
{{ end }}
