apiVersion: v1
kind: Service
metadata:
  name: {{ template "stash.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stash.labels" . | nindent 4 }}
  {{- if eq .Values.monitoring.agent "prometheus.io/builtin" }}
  annotations:
    prometheus.io/scrape: "true"
    {{- if .Values.monitoring.backup }}
    prometheus.io/pushgateway_path: "/metrics"
    prometheus.io/pushgateway_port: "56789"
    prometheus.io/pushgateway_scheme: "http"
    {{- end }}
    {{- if .Values.monitoring.operator }}
    prometheus.io/operator_path: "/metrics"
    prometheus.io/operator_port: "8443"
    prometheus.io/operator_scheme: "https"
    {{- end }}
  {{- end }}
spec:
  ports:
  # Port used to expose admission webhook apiserver
  - name: api
    port: 443
    targetPort: 8443
  # Port used to expose Prometheus pushgateway
  - name: pushgateway
    port: 56789
    protocol: TCP
    targetPort: 56789
  selector:
    app: "{{ template "stash.name" . }}"
    release: "{{ .Release.Name }}"
