apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appscode:stash:edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - stash.appscode.com
  resources:
  - restics
  - recoveries
  - repositories
  verbs: ["*"]
- apiGroups:
  - repositories.stash.appscode.com
  resources:
  - snapshots
  verbs: ["delete", "deletecollection", "get", "list"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appscode:stash:view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - stash.appscode.com
  resources:
  - restics
  - recoveries
  - repositories
  verbs: ["get", "list", "watch"]
- apiGroups:
  - repositories.stash.appscode.com
  resources:
  - snapshots
  verbs: ["get", "list"]
