apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: stash
  name: stashmariadbs.installer.stash.appscode.com
spec:
  group: installer.stash.appscode.com
  names:
    categories:
    - stash
    - appscode
    kind: StashMariaDB
    listKind: StashMariaDBList
    plural: stashmariadbs
    singular: stashmariadb
  preserveUnknownFields: false
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: StashMariaDBSpec is the schema for Stash MariaDB values file
          properties:
            backup:
              properties:
                args:
                  type: string
              required:
              - args
              type: object
            fullnameOverride:
              type: string
            image:
              properties:
                registry:
                  type: string
                repository:
                  type: string
                tag:
                  type: string
              required:
              - registry
              - repository
              - tag
              type: object
            nameOverride:
              type: string
            restore:
              properties:
                args:
                  type: string
              required:
              - args
              type: object
          required:
          - backup
          - image
          - restore
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
