{{ if .Values.crdInstaller.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stash-community.serviceAccountName" . }}-crd-installer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stash-community.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
{{ end }}
