apiVersion: stash.appscode.com/v1beta1
kind: Task
metadata:
  name: postgres-backup-12.4
spec:
  steps:
  - name: postgres-backup-12.4
    params:
    - name: outputDir
      value: /stash-tmp/output
  - name: update-status
    params:
    - name: outputDir
      value: /stash-tmp/output
