{{ if .Values.mysql.enabled }}
apiVersion: stash.appscode.com/v1beta1
kind: Function
metadata:
  name: 'mysql-restore-5.7.25'
  labels:
    {{- include "stash-catalog.labels" . | nindent 4 }}
spec:
  args:
  - restore-mysql
  - --provider=${REPOSITORY_PROVIDER:=}
  - --bucket=${REPOSITORY_BUCKET:=}
  - --endpoint=${REPOSITORY_ENDPOINT:=}
  - --region=${REPOSITORY_REGION:=}
  - --path=${REPOSITORY_PREFIX:=}
  - --secret-dir=/etc/repository/secret
  - --scratch-dir=/tmp
  - --enable-cache=${ENABLE_CACHE:=true}
  - --max-connections=${MAX_CONNECTIONS:=0}
  - --hostname=${HOSTNAME:=}
  - --source-hostname=${SOURCE_HOSTNAME:=}
  - --mysql-args=${args:={{ .Values.mysql.restore.args }}}
  - --wait-timeout=${waitTimeout:={{ .Values.waitTimeout}}}
  - --namespace=${NAMESPACE:=default}
  - --appbinding=${TARGET_NAME:=}
  - --snapshot=${RESTORE_SNAPSHOTS:=}
  - --output-dir=${outputDir:=}
  - --license-apiservice=${LICENSE_APISERVICE:=}
  image: '{{ include "catalog.registry" . }}/stash-mysql:5.7.25-v14'
  volumeMounts:
  - mountPath: /etc/repository/secret
    name: ${secretVolume}
{{ end }}
