apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "stash-ui-server.fullname" . }}
  labels:
    {{- include "stash-ui-server.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ui.stash.appscode.com
  resources:
  - "*"
  verbs: ["*"]
- apiGroups:
  - stash.appscode.com
  - repositories.stash.appscode.com
  resources:
  - "*"
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - nodes
  verbs: ["list"]
- apiGroups:
  - ""
  resources:
  - pods
  verbs: ["get", "list"]
- apiGroups:
  - ""
  resources:
  - events
  verbs: ["create"]
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs: ["get", "list", "watch"]
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs: ["get", "list", "watch"]
