{{- if eq "prometheus.io/operator" ( include "monitoring.agent" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stash-ui-server.fullname" . }}-metrics-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "stash-ui-server.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}
