# if license file is provided, then create a secret for license
{{- if include "appscode.license" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stash-enterprise.fullname" . }}-license
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stash-enterprise.labels" . | nindent 4 }}
type: Opaque
data:
  key.txt: {{ include "appscode.license" . | b64enc }}
{{- end }}
