{{- if and (eq .Values.monitoring.agent "prometheus.io/operator") (or .Values.monitoring.backup .Values.monitoring.operator) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stash-enterprise.fullname" . }}-metrics-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "stash-enterprise.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}