apiVersion: stash.appscode.com/v1beta1
kind: Function
metadata:
  name: perconaxtradb-restore-5.7
spec:
  args:
  - restore-percona-xtradb
  - --provider=${REPOSITORY_PROVIDER:=}
  - --bucket=${REPOSITORY_BUCKET:=}
  - --endpoint=${REPOSITORY_ENDPOINT:=}
  - --region=${REPOSITORY_REGION:=}
  - --path=${REPOSITORY_PREFIX:=}
  - --secret-dir=/etc/repository/secret
  - --scratch-dir=/tmp
  - --enable-cache=${ENABLE_CACHE:=true}
  - --max-connections=${MAX_CONNECTIONS:=0}
  - --hostname=${HOSTNAME:=}
  - --source-hostname=${SOURCE_HOSTNAME:=}
  - --xtradb-args=${args:=}
  - --target-app-replicas=${TARGET_APP_REPLICAS:=1}
  - --wait-timeout=${waitTimeout:=300}
  - --namespace=${NAMESPACE:=default}
  - --appbinding=${TARGET_NAME:=}
  - --snapshot=${RESTORE_SNAPSHOTS:=}
  - --output-dir=${outputDir:=}
  - --license-apiservice=${LICENSE_APISERVICE:=}
  image: stashed/stash-percona-xtradb:5.7-v7
  volumeMounts:
  - mountPath: /etc/repository/secret
    name: ${secretVolume}
