apiVersion: v1
description: 'Stash by AppsCode - Backup your Kubernetes Volumes'
name: stash
version: v0.9.0-rc.0
appVersion: v0.9.0-rc.0
home: https://github.com/stashed/stash
icon: https://cdn.appscode.com/images/icon/stash.png
sources:
  - https://github.com/stashed/stash
maintainers:
  - name: appscode
    email: support@appscode.com
