apiVersion: stash.appscode.com/v1beta1
kind: Function
metadata:
  name: etcd-restore-3.5.0
spec:
  args:
  - restore-etcd
  - --provider=${REPOSITORY_PROVIDER:=}
  - --bucket=${REPOSITORY_BUCKET:=}
  - --endpoint=${REPOSITORY_ENDPOINT:=}
  - --region=${REPOSITORY_REGION:=}
  - --path=${REPOSITORY_PREFIX:=}
  - --storage-secret-name=${REPOSITORY_SECRET_NAME:=}
  - --storage-secret-namespace=${REPOSITORY_SECRET_NAMESPACE:=}
  - --scratch-dir=/tmp
  - --enable-cache=${ENABLE_CACHE:=true}
  - --max-connections=${MAX_CONNECTIONS:=0}
  - --wait-timeout=${waitTimeout:=300}
  - --hostname=${HOSTNAME:=}
  - --source-hostname=${SOURCE_HOSTNAME:=}
  - --namespace=${NAMESPACE:=default}
  - --appbinding=${TARGET_NAME:=}
  - --etcd-args=${args:=}
  - --initial-cluster=${initialCluster:=}
  - --initial-cluster-token=${initialClusterToken:=}
  - --data-dir=${dataDir:=}
  - --workload-kind=${workloadKind:=}
  - --workload-name=${workloadName:=}
  - --output-dir=${outputDir:=}
  - --license-apiservice=${LICENSE_APISERVICE:=}
  - --invoker-kind=${INVOKER_KIND:=}
  - --invoker-name=${INVOKER_NAME:=}
  - --image=${ADDON_IMAGE:=}
  - --secret-name=${REPOSITORY_SECRET_NAME:=}
  - --snapshots=${RESTORE_SNAPSHOTS:=}
  image: stashed/stash-etcd:3.5.0-v2
