{{"{{ if .Values."}}{{ .app }}{{".enabled }}"}}
apiVersion: {{ .object.apiVersion }}
kind: {{ .object.kind }}
metadata:
  name: '{{ .object.metadata.name }}'
  labels:
    {{"{{- include \"stash-catalog.labels\" . | nindent 4 }}"}}
spec:
  {{- .object.spec | toYaml | nindent 2 }}
{{"{{ end }}"}}
