project:
  name: Stash Catalog
  shortName: Stash Catalog
  url: https://github.com/stashed
  description: Catalog of Stash Addons
  app: Stash catalog
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: stash-catalog
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.14+
release:
  name: stash-catalog
  namespace: stash
