apiVersion: metrics.appscode.com/v1alpha1
kind: MetricsConfiguration
metadata:
  name: stash-appscode-com-repository
spec:
  targetRef:
    apiVersion: stash.appscode.com/v1alpha1
    kind: Repository
  metrics:
    - name: created
      help: "Unix creation timestamp of this Repository"
      type: gauge
      field:
        path: .metadata.creationTimestamp
        type: DateTime
      metricValue:
        valueFromPath: .metadata.creationTimestamp
