apiVersion: stash.appscode.com/v1beta1
kind: Function
metadata:
  name: update-status
  labels:
    {{- include "stash.labels" . | nindent 4 }}
spec:
  image: {{ .Values.operator.registry }}/{{ .Values.operator.repository }}:{{ .Values.operator.tag }}
  args:
    - update-status
    - --namespace=${NAMESPACE:=default}
    - --repository=${REPOSITORY_NAME:=}
    - --backup-session=${BACKUP_SESSION:=}
    - --restore-session=${RESTORE_SESSION:=}
    - --output-dir=${outputDir:=}
    - --enable-status-subresource=${ENABLE_STATUS_SUBRESOURCE:=false}
