apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "stash-community.fullname" . }}
  labels:
    {{- include "stash-community.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ["*"]
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs: ["get", "patch", "delete"]
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs: ["delete", "get", "list", "watch", "patch"]
- apiGroups:
  - stash.appscode.com
  resources:
  - "*"
  verbs: ["*"]
- apiGroups:
  - appcatalog.appscode.com
  resources:
  - "*"
  verbs: ["*"]
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs: ["get", "list", "watch", "patch"]
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list", "watch", "create", "delete", "patch"]
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs: ["get", "list", "watch", "patch"]
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs: ["create", "update", "get", "list", "watch", "delete"]
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs: ["get", "list", "watch", "create", "patch"]
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs: ["get"]
- apiGroups:
  - ""
  resources:
  - secrets
  verbs: ["get", "list", "create", "patch"]
- apiGroups:
  - ""
  resources:
  - events
  verbs: ["get", "list", "create", "patch"]
- apiGroups:
  - ""
  resources:
  - nodes
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs: ["get", "create", "list", "delete", "deletecollection"]
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs: ["get", "create", "patch", "delete"]
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - roles
  - rolebindings
  - clusterrolebindings
  verbs: ["get", "list", "create", "delete", "patch"]
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs: ["get", "list", "watch", "patch"]
{{- if and (.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy") .Values.security.podSecurityPolicies }}
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs: ["use"]
  resourceNames:
  {{- range $x := .Values.security.podSecurityPolicies }}
  - {{ $x }}
  {{- end }}
{{- end }}
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  - volumesnapshotcontents
  - volumesnapshotclasses
  verbs: ["create", "get", "list", "watch", "patch", "delete"]
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs: ["get"]
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs: ["*"]
- apiGroups:
  - apps
  resources:
  - daemonsets/finalizers
  - deployments/finalizers
  - statefulsets/finalizers
  verbs: ["update"]
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs/finalizers
  verbs: ["update"]

