# if license file is provided, then create a secret for license
  {{- if .Values.license }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stash-community.fullname" . }}-license
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "stash-community.labels" . | nindent 4 }}
type: Opaque
data:
  key.txt: {{ .Values.license | b64enc }}
{{- end }}
