apiVersion: stash.appscode.com/v1beta1
kind: Task
metadata:
  name: postgres-restore-18.2
spec:
  steps:
  - name: postgres-restore-18.2
    params:
    - name: outputDir
      value: /stash-tmp/output
  - name: update-status
    params:
    - name: outputDir
      value: /stash-tmp/output
