apiVersion: stash.appscode.com/v1beta1
kind: Task
metadata:
  name: redis-backup-6.2.5
spec:
  steps:
  - name: redis-backup-6.2.5
    params:
    - name: outputDir
      value: /tmp/output
    - name: secretVolume
      value: secret-volume
  - name: update-status
    params:
    - name: outputDir
      value: /tmp/output
    - name: secretVolume
      value: secret-volume
  volumes:
  - name: secret-volume
    secret:
      secretName: ${REPOSITORY_SECRET_NAME}
