apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stash-community.serviceAccountName" . }}-cleaner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stash-community.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
