{{ if .Values.crdInstaller.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "stash-enterprise.fullname" . }}-crd-installer
  labels:
    {{- include "stash-enterprise.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs: ["*"]
  - apiGroups:
      - stash.appscode.com
    resources:
      - "*"
    verbs: ["*"]
{{ end }}
