apiVersion: stash.appscode.com/v1beta1
kind: Task
metadata:
  name: kubedump-backup-0.2.0
spec:
  steps:
  - name: kubedump-backup-0.2.0
    params:
    - name: outputDir
      value: /stash-tmp/output
  - name: update-status
    params:
    - name: outputDir
      value: /stash-tmp/output
