apiVersion: stash.appscode.com/v1beta1
kind: Task
metadata:
  name: mongodb-restore-4.0.11
spec:
  steps:
  - name: mongodb-restore-4.0.11
    params:
    - name: outputDir
      value: /stash-tmp/output
  - name: update-status
    params:
    - name: outputDir
      value: /stash-tmp/output
