name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Prepare Host
        run: |
          sudo apt-get -qq update || true
          sudo apt-get install -y bzr
          # install yq
          curl -fsSL -o yqq https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64
          chmod +x yqq
          sudo mv yqq /usr/local/bin/yqq
          pipx install yq
          # install kubectl
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.25.0/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Run checks
        run: |
          ./hack/scripts/update-chart-dependencies.sh
          make ci

      - name: Check metrics configuration
        run: |
          # install metrics-configuration-checker
          curl -fsSL -o metrics-configuration-checker https://github.com/kmodules/metrics-configuration-checker/releases/download/v0.0.1/metrics-configuration-checker-linux-amd64
          chmod +x metrics-configuration-checker
          sudo mv metrics-configuration-checker /usr/local/bin/metrics-configuration-checker
          # check stash-metrics chart
          metrics-configuration-checker --content=./charts/stash-metrics/templates/

  kubernetes:
    name: Kubernetes
    runs-on: ubuntu-24.04
    needs: build
    strategy:
      matrix:
        k8s: [v1.28.15, v1.30.13, v1.32.5, v1.33.2]
    steps:
      - uses: actions/checkout@v4

      - name: Install yq
        run: |
          curl -fsSL -o yqq https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64
          chmod +x yqq
          sudo mv yqq /usr/local/bin/yqq

      - name: Create Kubernetes ${{ matrix.k8s }} cluster
        id: kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.29.0
          image: kindest/node:${{ matrix.k8s }}

      - name: Prepare cluster for testing
        id: local-path
        env:
          USERNAME: 1gtm
          REGISTRY_SECRET: regcred
        run: |
          echo "waiting for nodes to be ready ..."
          kubectl wait --for=condition=Ready nodes --all --timeout=5m
          kubectl get nodes
          echo
          echo "install helm 3"
          pushd /usr/local/bin && sudo curl -fsSLO https://github.com/x-helm/helm/releases/latest/download/helm && sudo chmod +x helm && popd

      - name: Issue License
        env:
          BYTEBUILDERS_LICENSE_TOKEN: ${{ secrets.BYTEBUILDERS_LICENSE_TOKEN }}
        run: |
          export KUBECONFIG="${HOME}/.kube/config"
          CLUSTER_UID=$(kubectl get ns kube-system -o=jsonpath='{.metadata.uid}')
          LICENSE_KEY=$(curl -X POST -d "name=1gtm&email=1gtm@appscode.com&product=stash-enterprise&cluster=${CLUSTER_UID}&tos=true&token=${BYTEBUILDERS_LICENSE_TOKEN}" https://license-issuer.appscode.com/issue-license)
          # ref: https://github.com/mikefarah/yq/issues/230#issuecomment-487458629
          yqq w -i ./charts/stash-community/ci/ci-values.yaml license --tag '!!str' -- "${LICENSE_KEY}"
          yqq w -i ./charts/stash-enterprise/ci/ci-values.yaml license --tag '!!str' -- "${LICENSE_KEY}"

      - name: Test charts
        run: |
          export KUBECONFIG="${HOME}/.kube/config"
          ./hack/scripts/update-chart-dependencies.sh
          ./hack/scripts/ct.sh
