{{ if .Values.kubedump.enabled }}
apiVersion: stash.appscode.com/v1beta1
kind: Task
metadata:
  name: 'kubedump-backup-0.1.0'
  labels:
    {{- include "stash-catalog.labels" . | nindent 4 }}
spec:
  steps:
  - name: kubedump-backup-0.1.0
    params:
    - name: outputDir
      value: /stash-tmp/output
  - name: update-status
    params:
    - name: outputDir
      value: /stash-tmp/output
{{ end }}
